### ISSUE TITLE
Gjør det mulig å kjøre timebot første dag i ny måned

### ISSUE THREAD

**Issue by trond-oydna** [blankoslo/floq-timebot#9]
Behov:
I Blank må ansatte føre alle timer ut måneden ved månedslutt, akkurat som ved ukeslutt. Men timebot sier ikke i fra om dette, så ansatte må sjekkes og bli fulgt opp individuelt.

Hvorfor dette ikke kan løses i dag:
Timebot sjekker time ført forrige uke.
Så f.eks. hvis ny måned er på en torsdag og timebot blir kjørt vil den sjekke uken før, og ikke dagene denne uken frem til i dag.

Foreslått løsning:
Gjør det mulig for timebot å sjekke førte timer denne uken frem til dagens dato.
Dermed kan den settes opp i Cloud Run Jobs til å bli kjørt første dag hver måned.
Teksten burde også endres litt så den ikke sier "sist uke".

**Comment by kmidtlid** [comment]
Løsning: Sjekk om det er den første dagen i måneden. Hvis det er første dag (og ikke en mandag som vanlig run) sjekk timer ført denne uken, ellers kjør som vanlig. Lagt til trigger for å kjøre jobben første dag i hver måned

#10
* Sjekk timer ført denne uken frem til og med gårsdagens dato (siden vi kjører første dag hver måned)
* Lagt til støtte for testing (dry runs)
* Oppdatert tekst til å si "denne uken" om vi sjekker denne uken

#11 :
* Lagt til variabler for å teste "første dag i måneden"-logikk
